config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home' 

  resources :cards
  resources :users
  resources :pages
  
  get 'pages/allcards'
  get 'about' => 'pages#about'
  get 'cards' => 'cards#cards'
  get 'allcards' => 'pages#allcards'
  get 'usercards' => 'cards#user_cards'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :title, presence: true
  validates :mood, presence: true
  validates :user_id, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  ## User proprieties
  has_many :cards    
  attr_accessor :remember_token

  ## User Validation
  # Setup
  before_save { self.email = self.email.downcase }
  MAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d]\-)*\.[a-z]+\z/i

  validates :name, presence: true, length: {minimum: 3, maximum: 30}
  validates :email, 
    presence: true,
    length: {minimum: 6, maximum: 70},
    uniqueness: { case_sensitive: false },
    format: { with: MAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8, maximum: 255}

  # Returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
      SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token) )
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authentificated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :content, :mood)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cards = Card.all
  end

  def about
  end

  def allcards
    @cards = Card.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user) 
      redirect_to user_url(user)
      flash[:success] = "Welcome back #{user.name} !"
    else
      sleep(0.3)
      flash.now[:warning] = "Invalid email or password. Try again !"
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You logged out."
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success]='Account created ! You can now log-in !'
        format.html { redirect_to login_url }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def glyph(glyph)
    span=" <span class='fa fa-#{glyph}'></span> "
    span.html_safe
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
      session[:user_id] = user.id
  end 

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the curent user
  def log_out
    session.delete(:user_id)
    forget(@current_user)
    @current_user=nil
  end

  # Load the current user from the id stored in the session
  def current_user
    # If a session exists
    if (user_id = session[:user_id])
      # Understand : if @curent_user.nil ? then execute ... if not, leave it alone
      @current_user ||= User.find_by(id: user_id)
      # We use find_by because it returns a nil value it it fails, where find() raises and exception.
    # Else, if a signed cookie containing user_id exists
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authentificated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #return true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end


end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size="50x50")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class:"gravatar rounded", size: size )
  end

end

app/views/cards/_card.html.erb
<div class="ticket ticket-mood-<%= card.mood.downcase %> d-flex px-4 align-items-center">
  <div style="height: 100%">
  <% if card.content.blank? %>
    <h1><%= card.title %></h1>
  <% else %>
      <h3><%= card.title %></h3>
      <p><%= card.content %></p>
  <% end %>
  </div>
</div> 
<div class="row">
  <div class="col">
    <div class="text-left"><small><%= link_to "Edit".html_safe, edit_card_path(card) %></small></div>
  </div>
  <div>
    <div class="text-right"><small><%= link_to "#{glyph('trash')}delete".html_safe, card, method: :delete, data: { confirm: 'Are you sure?' } %></small></div>
  </div>
</div>

app/views/cards/_form.html.erb
<% if card.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">This card could not be saved because :
      <ul class="my-0">
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="ticket">
   <%= form_with(model: card, local: true) do |form| %>
    
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :mood %>
      <%= form.select :mood,
        ["Proactive", "Serious", "Fun", "Empowering", "Interesting"],
        {}, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<%end%>

<h1>Card list</h1>
  <table class="table table-light shadow-sm">
    <thead style="border: 0px;">
      <tr>
        <th>Mood</th>
        <th>Title</th>
        <th>Description</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% current_user.cards.each do |card| %>
        <tr>
          <td><%= card.mood %></td>
          <td><%= card.title %></td>
          <td><%= card.content.truncate(30) %></td>
          <td><%= link_to 'Show', card %><br>
          <%= link_to 'Edit', edit_card_path(card) %><br>
          <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/cards/new.html.erb
<h1>New Card</h1>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<%end%>

<div class="alert alert-warning">Do <u>not</u> give any personnal info here.</div>
<%= render 'form', card: @card %>

<%= link_to 'Back', root_url, class: "btn btn-dark", style: "margin: 15px;" %>

app/views/cards/show.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<%end%>

<%= render 'card', card: @card %>

app/views/cards/user_cards.erb
<h1>My cards :</h1><br/>
<%if current_user.cards.empty?%>
  <div class="ticket ticket-notify d-flex px-4 align-items-center">
    <div style="height: 100%">
      <h3>You dont have any card yet !</h3>
      <p>Use the geen "<%= glyph("plus") %>" button to create your first card.</p>
    </div>
  </div>
<%else%>
  <% current_user.cards.each do |card| %>
    <%= render 'card', card: card %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>WatnoW</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <link rel="manifest" href="/manifest.json" />
    <%= favicon_link_tag 'favicon.png', :rel => 'icon', :type =>  'image/png' %>

    <!-- Bootstrap 4.1.13 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

  </head>

  <body>
    <main role="main" class="container-fluid px-0">
      
      <!-- Navbar -->
      <%= render "parts/navbar"%>
      <br/>

      <!-- Main part -->
      <div class="row mx-0"> 
        <div class= "col-10 col-sm-8 col-md-6 col-lg-4 mx-auto px-0">
          <!-- Flash messages placeholder -->
          <% flash.each do |message_type, message| %>
            <%if message_type != 'notice' %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <%end%>
          <%end%>
          <%= yield %><br/>
        </div>

        <%= debug(params) if Rails.env.development? %>
      </div>
      
      <div class="row">
        <%= render "parts/bottom"%>
      </div>
    </main>

    
  </body>
  <%= render "parts/scripts"%>
</html>

app/views/pages/about.html.erb
<div class="ticket">
  <h1>What is this app about ?</h1>
  <p>Did you ever feel bored and went on Facebook or YouTube just because you didn't know what else to do ? 
  Or even because you didn't even try to thing about anything else to do ?
  Yeah, so did I. In fact, this happen to me so often that it’s almost become a reflex.<br/>
  And I don’t like that.</p>

  <p>I actually have many things I enjoy doing : reading a book, listening to a podcast… 
  But when I have time to do one of these, I suddenly forget about them and go back to this habit of watching YouTube videos.</p>

  <p>I created WatnoW as a way for me to remember all this small activities I enjoy doing when the time comes.
  When I feel like I have time, I pop-up WatnoW and it suggests something to do, breaking the never ending circle of 
  switching between  social medias.</p> 

  <p>You can create your own cards to add activities you want to see suggested to you.
  Assign a “type” to them so they will pop up with nice colors.</p>

  <h2>Share this app !</h2>
  <%= image_tag("qr-code.png", size: "200x200", alt: "WatnoW QR-Code", class: "rounded mx-auto d-block") %>
  <center><small class="text-muted"><em>Share this QR-code</em></small></center>
  <h2>Privacy</h2>

  <p>No data will be given to any third party, but be aware : <em>none of those are encrypted</em>. If this app is hacked, every single card you created will potentially be exposed, so don’t store any sensitive information here. You’ve been warned. 
</div>

app/views/pages/allcards.html.erb
<% @cards.each do |card|  %>
  <%= render 'cards/card', card: card %>
  <br>
<%end%>

app/views/pages/home.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<%end%>

<% if logged_in? %>
  <%if @current_user.cards.empty?%>
    <div class="ticket ticket-notify d-flex px-4 align-items-center">
      <h1>Get Started !</h1>
      <p>Press the "+" to create your first activity card.</p>
    </div>
  <%else%>
    <% card = @current_user.cards.sample  %>
      <%= render 'cards/card', card: card %>
  <%end%>
<%else%>
  <div class="ticket ticket-notify d-flex px-4 align-items-center">
    <h3>Welcome on WatnoW</h3>
    <p>Log-in or Create an account to use this app.
    <br/>It's easy and free ! go ahead !</p>
  </div>
  <div class="row my-3">
    <div class="col text-center ">
      <%= link_to "Create an account", new_user_url, class: "btn btn-link btn-small" %>
    </div>
    <div class="col text-center">
      <%= link_to "Log in", login_url, class: "btn btn-primary btn-small" %>
    </div>
  </div>
<%end%>

app/views/parts/_bottom.html.erb
<% if current_page?(controller: "pages", action: "about") or
      current_page?(controller: "users", action: "new") or
      current_page?(controller: "users", action: "create") or
      current_page?(controller: "sessions", action: "new") %>
  <% # no fab here %>
<% elsif !logged_in? %>
  <%= link_to glyph('sign-in-alt'), login_url, class: "fab" %>
<%else%>
  <%= link_to glyph('plus'), new_card_url, class: "fab" %>
<%end%>

app/views/parts/_footer.html.erb
<div class="container">
  hello worlds
</div>

app/views/parts/_navbar.html.erb
<nav class="navbar navbar-expand-sm mx-0 navbar-light bg-light shadow-sm w-100">
  <a class="navbar-brand" href="<%= root_url %>">
    <%= image_tag("icon-256.png", size: "30x30", alt: "WatnoW Icon", class: "d-inline-block align-top") %>
    WatnoW
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "#{glyph('home')}Home".html_safe, root_url, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "#{glyph('question')}About".html_safe, about_url, class: "nav-link" %>
      </li>

      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "#{glyph('scroll')}Cards".html_safe, usercards_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "#{glyph('sign-out-alt')}Log out".html_safe, logout_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "#{glyph('user')} Hi #{@current_user.name} !".html_safe, user_path(current_user), class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "#{glyph('sign-in-alt')}Log in".html_safe, login_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "#{glyph('pen-alt')}Sign up".html_safe, signup_url, class: "nav-link" %>
        </li>
      <%end%> 
    </ul>
  </div>
</nav>

app/views/parts/_scripts.html.erb
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>

// Register the worker
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('/sw.js').then(function(registration) {
      // Registration was successful
      console.log('ServiceWorker registration successful with scope: ', registration.scope);
    }, function(err) {
      // registration failed :(
      console.log('ServiceWorker registration failed: ', err);
    });
  });
}



</script>

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger ">Oooups... You made <%= pluralize(user.errors.count, "mistake") %> :
      <ul class="text-weight-light my-0">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="ticket">
  <%= form_with(model: user, url: signup_path, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name,  class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :pasword %>
      <%= form.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation, "Confirmation" %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="actions text-center">
      <%= form.submit "Submit", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="ticket">
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="align-middle"><%= user.name %></td>
          <td class="align-middle"><%= user.email %><br/>
          <%= link_to 'Show', user , class:"btn btn-sm btn-outline-primary"%> 
          <%= link_to 'Edit', edit_user_path(user) , class:"btn btn-sm btn-outline-primary" %> 
          <%= link_to 'Destroy', user  , class:"btn btn-sm btn-outline-primary", method: :delete, data: { confirm: 'Are you sure?' } %> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to '<span class="fa fa-plus"></span> New User'.html_safe, new_user_path, class: "btn btn-success" %>

app/views/users/new.html.erb
<h1>Sign-up !</h1>

<%= render 'form', user: @user %>

<div class="row my-3">
  <p class="tex-right">Already have an account ? <%= link_to 'Log in !', login_url %></p>
</div>

app/views/users/show.html.erb
<div class="ticket ticket-notify d-flex px-4 align-items-center">
  <div style="height: 100%">
    <h3><%= gravatar_for @user, "35x35" %> Hello <%= @user.name %> !</h3>
    <ul>
      <li><%= @user.email %></li>
      <li>registrered on <%= @user.created_at.to_formatted_s(:long) %></li>
      <li>You created <%= pluralize(@user.cards.count, "card") %></li>
    </ul>
  </div>
</div> 

<div class="row">
  <div class="col text-left"><small><%= link_to '<span class="fa fa-user-edit"> edit</span>'.html_safe, edit_user_path(@user) %></small></div>
  <div class="col text-right"><small><%= link_to '<span class="fa fa-trash-alt"> delete</span>'.html_safe, @user, method: :delete, data: { confirm: 'Are you sure?' } %></small></div>
</div>